"""
setup.py -- Interactive first-run configuration wizard for PocketScan.
Run once on the Raspberry Pi:
    python3 scripts/setup.py
"""
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = ROOT / ".env"


def ask(prompt: str, current: str = "") -> str:
    hint = f" [{current}]" if current else ""
    val = input(f"{prompt}{hint}: ").strip()
    return val if val else current


def main():
    print()
    print("=" * 56)
    print("  PocketScan — First-Run Setup Wizard")
    print("=" * 56)
    print()

    # Load existing values if .env exists
    existing = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text().splitlines():
            if "=" in line and not line.startswith("#"):
                k, _, v = line.partition("=")
                existing[k.strip()] = v.strip()

    print("Step 1/3 — Telegram Bot Token")
    print("  Create a bot at https://t.me/BotFather  → /newbot")
    token = ask("  Paste your Bot Token", existing.get("TELEGRAM_BOT_TOKEN", ""))
    if not token:
        print("[ERROR] Bot token cannot be empty. Aborting.")
        sys.exit(1)

    print()
    print("Step 2/3 — Admin Telegram User ID")
    print("  Find your ID by messaging https://t.me/userinfobot")
    admin_id = ask("  Your Telegram User ID", existing.get("ADMIN_USER_ID", ""))
    if not admin_id.isdigit():
        print("[ERROR] User ID must be a number. Aborting.")
        sys.exit(1)

    print()
    print("Step 3/3 — Photo Storage Directory")
    photo_dir = ask(
        "  Where to save photos on this device",
        existing.get("PHOTO_DIR", str(ROOT / "photos")),
    )
    Path(photo_dir).mkdir(parents=True, exist_ok=True)

    # Write .env
    env_content = f"""# PocketScan configuration — generated by setup.py
TELEGRAM_BOT_TOKEN={token}
ADMIN_USER_ID={admin_id}
PHOTO_DIR={photo_dir}
LOG_LEVEL=INFO
"""
    ENV_FILE.write_text(env_content)
    os.chmod(ENV_FILE, 0o600)   # only owner can read secrets

    print()
    print("=" * 56)
    print(f"  Config saved to {ENV_FILE}")
    print()
    print("  Start the bot:")
    print("    python3 bot/main.py")
    print()
    print("  Or enable the systemd service (see README):")
    print("    sudo systemctl enable pocketscan && sudo systemctl start pocketscan")
    print("=" * 56)
    print()


if __name__ == "__main__":
    main()
